import { Inter } from "@next/font/google";
import Head from "next/head";
import Header from "../components/Header";
import Nav from "../components/Nav";
import Results from "../components/Results";
import requests from "../utils/requests";

const inter = Inter({ subsets: ["latin"] });

export default function Home(prop) {
  console.log(prop);
  return (
    <>
      <Head>
        <title>Hulu</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/Redzulu-favicon.png" />
      </Head>

      <Header />
      <Nav />
      <Results />
    </>
  );
}

export async function getServerSideProps(context) {
  const genre = context.query.genre;

  const url = `https://api.themoviedb.org/3${
    requests[genre]?.url || requests.fetchTrending.url
  }`;
  console.log(url);

  const request = await fetch(
    `https://api.themoviedb.org/3${
      requests[genre]?.url || requests.fetchTrending.url
    }`
  ).then((res) => res.json());

  return {
    props: {
      results: request.results,
    },
  };
}
